# Important: 127.0.0.1 should be replaced by the external ip address of the machine
version: "3"

services:
  gatewayd:
    image: fedimint/gatewayd:v0.1.3
    command: gatewayd lnd
    environment:
      # Path to folder containing gateway config and data files
      - FM_GATEWAY_DATA_DIR=/gateway_data
      # Gateway webserver listen address
      - FM_GATEWAY_LISTEN_ADDR=0.0.0.0:8175
      # Public URL from which the webserver API is reachable
      - FM_GATEWAY_API_ADDR=https://gatewayd.fedi.sanctions.gay
      # Gateway webserver authentication password
      - FM_GATEWAY_PASSWORD=$GATEWAY_PASSWORD
      # Configured gateway routing fees Format: <base_msat>,<proportional_millionths>
      - FM_GATEWAY_FEES=1000,0
      # LND RPC address
      - FM_LND_RPC_ADDR=https://host.docker.internal:10009
      # LND TLS cert file path
      - FM_LND_TLS_CERT=/lnd_data/tls.cert
      # LND macaroon file path
      - FM_LND_MACAROON=/lnd_data/data/chain/bitcoin/mainnet/admin.macaroon
    volumes:
      - ~/.fedi/gateway:/gateway_data
      - ~/.lnd:/lnd_data:ro
    ports:
      - "8175:8175"
      - "8176:8080"
    depends_on:
      - lnd
    restart: always
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway-ui:
    image: fedimintui/gateway-ui:0.1
    # image: gateway-ui
    ports:
      - "0.0.0.0:8177:3001"
    environment:
      - PORT=3001
      - REACT_APP_FM_GATEWAY_API=https://gatewayd.fedi.sanctions.gay
      - REACT_APP_FM_GATEWAY_PASSWORD=$GATEWAY_PASSWORD
    depends_on:
      - gatewayd
    restart: always
    platform: linux/amd64
